services:
  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - hospital-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: hospital_keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    command: ["start-dev"]
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hospital-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/hospital_spring
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: hospital
      KEYCLOAK_CLIENT_ID: hospital-spring-client
      KEYCLOAK_CLIENT_SECRET: 3ZQd90sK2K3EZLjqmNhjYWmAlLYylyU0
    depends_on:
      - mysql
      - keycloak
    networks:
      - hospital-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8080
        - VITE_KEYCLOAK_URL=http://localhost:8081
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hospital-network

volumes:
  mysql-data:

networks:
  hospital-network:
    driver: bridge
